export default `
APP_PREFIX = "$APP_PREFIX"
APP_TOKEN = "$APP_TOKEN"

PRESET_COMMAND_AUTO_REMOVE = $PRESET_COMMAND_AUTO_REMOVE

PARTIAL_MESSAGE = $PARTIAL_MESSAGE
PARTIAL_CHANNEL = $PARTIAL_CHANNEL
PARTIAL_REACTION = $PARTIAL_REACTION

INTENT_GUILDS = $INTENT_GUILDS
INTENT_GUILD_MEMBERS = $INTENT_GUILD_MEMBERS
INTENT_GUILD_BANS = $INTENT_GUILD_BANS
INTENT_GUILD_EMOJIS_AND_STICKERS = $INTENT_GUILD_EMOJIS_AND_STICKERS
INTENT_GUILD_INTEGRATIONS = $INTENT_GUILD_INTEGRATIONS
INTENT_GUILD_WEBHOOKS = $INTENT_GUILD_WEBHOOKS
INTENT_GUILD_INVITES = $INTENT_GUILD_INVITES
INTENT_GUILD_VOICE_STATES = $INTENT_GUILD_VOICE_STATES
INTENT_GUILD_PRESENCES = $INTENT_GUILD_PRESENCES
INTENT_GUILD_MESSAGES = $INTENT_GUILD_MESSAGES
INTENT_GUILD_MESSAGE_REACTIONS = $INTENT_GUILD_MESSAGE_REACTIONS
INTENT_GUILD_MESSAGE_TYPING = $INTENT_GUILD_MESSAGE_TYPING
INTENT_DIRECT_MESSAGES = $INTENT_DIRECT_MESSAGES
INTENT_DIRECT_MESSAGE_REACTIONS = $INTENT_DIRECT_MESSAGE_REACTIONS
INTENT_DIRECT_MESSAGE_TYPING = $INTENT_DIRECT_MESSAGE_TYPING

MESSAGE_COMMAND_MISSING_PERMISSION = "You're not authorized to execute this command"
MESSAGE_COMMAND_MISSING_ROLES = "You're not authorized to execute this command"
MESSAGE_ENVIRONMENT_FILE_PREFIX_MISSING = "The prefix is missing in the environment file."
MESSAGE_ENVIRONMENT_FILE_TOKEN_MISSING = "The token is missing in the environment file."
MESSAGE_ENVIRONMENT_FILE_MISSING = "Environment file is missing, please create one."
`